INFO 2021-12-20 02:30:16,759 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 02:30:29,269 basehttp 179 "GET / HTTP/1.1" 200 10697
WARNING 2021-12-20 02:30:29,383 basehttp 179 "GET /static/admin/css/fonts.css HTTP/1.1" 404 1816
INFO 2021-12-20 02:30:34,326 basehttp 179 "GET / HTTP/1.1" 200 10697
WARNING 2021-12-20 02:30:34,389 basehttp 179 "GET /static/admin/css/fonts.css HTTP/1.1" 404 1816
INFO 2021-12-20 02:30:34,750 basehttp 179 "GET / HTTP/1.1" 200 10697
WARNING 2021-12-20 02:30:34,801 basehttp 179 "GET /static/admin/css/fonts.css HTTP/1.1" 404 1816
INFO 2021-12-20 02:45:51,080 autoreload 643 Watching for file changes with StatReloader
WARNING 2021-12-20 02:48:32,384 basehttp 179 "GET /static/index.html HTTP/1.1" 404 1789
INFO 2021-12-20 02:48:42,669 basehttp 179 "GET /index.html HTTP/1.1" 200 10697
WARNING 2021-12-20 02:48:42,821 basehttp 179 "GET /static/admin/css/fonts.css HTTP/1.1" 404 1816
WARNING 2021-12-20 02:50:35,496 basehttp 179 "GET /static/base.html HTTP/1.1" 404 1786
INFO 2021-12-20 02:51:35,657 autoreload 257 /home/guoliangmiao/git_workdir/miduo_mall/miduo_mall/settings.py changed, reloading.
INFO 2021-12-20 02:51:36,152 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 02:51:39,996 basehttp 179 "GET /static/base.html HTTP/1.1" 200 6037
WARNING 2021-12-20 02:51:40,073 basehttp 179 "GET /static/%7B%7B%20static('css/main.css')%20%7D%7D HTTP/1.1" 404 1885
WARNING 2021-12-20 02:51:40,083 basehttp 179 "GET /static/%7B%7B%20static('css/reset.css')%20%7D%7D HTTP/1.1" 404 1888
WARNING 2021-12-20 02:51:40,085 basehttp 179 "GET /static/%7B%7B%20static('js/axios-0.18.0.min.js')%20%7D%7D HTTP/1.1" 404 1915
WARNING 2021-12-20 02:51:40,116 basehttp 179 "GET /static/%7B%7B%20static('js/jquery-1.12.4.min.js')%20%7D%7D HTTP/1.1" 404 1918
WARNING 2021-12-20 02:51:40,120 basehttp 179 "GET /static/%7B%7B%20static('js/host.js')%20%7D%7D HTTP/1.1" 404 1879
WARNING 2021-12-20 02:51:40,139 basehttp 179 "GET /static/%7B%7B%20static('js/vue-2.5.16.js')%20%7D%7D HTTP/1.1" 404 1897
WARNING 2021-12-20 02:51:40,144 basehttp 179 "GET /static/%7B%7B%20static('js/common.js')%20%7D%7D HTTP/1.1" 404 1885
WARNING 2021-12-20 02:51:40,151 basehttp 179 "GET /static/%7B%7B%20static('js/base.js')%20%7D%7D HTTP/1.1" 404 1879
WARNING 2021-12-20 02:51:40,160 basehttp 179 "GET /static/%7B%7B%20static('images/logo.png')%20%7D%7D HTTP/1.1" 404 1894
WARNING 2021-12-20 02:51:40,161 basehttp 179 "GET /static/%7B%7B%20static('js/axios-0.18.0.min.js')%20%7D%7D HTTP/1.1" 404 1915
WARNING 2021-12-20 02:51:40,180 basehttp 179 "GET /static/%7B%7B%20static('js/jquery-1.12.4.min.js')%20%7D%7D HTTP/1.1" 404 1918
WARNING 2021-12-20 02:51:40,202 basehttp 179 "GET /static/%7B%7B%20static('js/common.js')%20%7D%7D HTTP/1.1" 404 1885
WARNING 2021-12-20 02:51:40,203 basehttp 179 "GET /static/%7B%7B%20static('images/logo.png')%20%7D%7D HTTP/1.1" 404 1894
WARNING 2021-12-20 02:51:40,283 basehttp 179 "GET /static/%7B%7B%20static('js/base.js')%20%7D%7D HTTP/1.1" 404 1879
INFO 2021-12-20 02:54:41,167 autoreload 257 /home/guoliangmiao/git_workdir/miduo_mall/miduo_mall/settings.py changed, reloading.
INFO 2021-12-20 02:54:41,625 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 02:55:11,146 autoreload 257 /home/guoliangmiao/git_workdir/miduo_mall/miduo_mall/settings.py changed, reloading.
INFO 2021-12-20 02:55:11,629 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 02:59:13,413 basehttp 179 "GET /index.html HTTP/1.1" 200 10697
WARNING 2021-12-20 02:59:13,538 basehttp 179 "GET /static/admin/css/fonts.css HTTP/1.1" 404 1822
INFO 2021-12-20 02:59:13,558 basehttp 179 "GET /favicon.ico HTTP/1.1" 200 10697
WARNING 2021-12-20 02:59:43,438 basehttp 179 "GET /static/dase.html HTTP/1.1" 404 1792
INFO 2021-12-20 02:59:58,754 basehttp 179 "GET /static/base.html HTTP/1.1" 200 6037
WARNING 2021-12-20 02:59:58,896 basehttp 179 "GET /static/%7B%7B%20static('css/reset.css')%20%7D%7D HTTP/1.1" 404 1894
WARNING 2021-12-20 02:59:58,906 basehttp 179 "GET /static/%7B%7B%20static('js/vue-2.5.16.js')%20%7D%7D HTTP/1.1" 404 1903
WARNING 2021-12-20 02:59:58,918 basehttp 179 "GET /static/%7B%7B%20static('js/host.js')%20%7D%7D HTTP/1.1" 404 1885
WARNING 2021-12-20 02:59:58,929 basehttp 179 "GET /static/%7B%7B%20static('js/jquery-1.12.4.min.js')%20%7D%7D HTTP/1.1" 404 1924
WARNING 2021-12-20 02:59:58,937 basehttp 179 "GET /static/%7B%7B%20static('css/main.css')%20%7D%7D HTTP/1.1" 404 1891
WARNING 2021-12-20 02:59:58,952 basehttp 179 "GET /static/%7B%7B%20static('js/axios-0.18.0.min.js')%20%7D%7D HTTP/1.1" 404 1921
WARNING 2021-12-20 02:59:58,964 basehttp 179 "GET /static/%7B%7B%20static('js/common.js')%20%7D%7D HTTP/1.1" 404 1891
WARNING 2021-12-20 02:59:58,984 basehttp 179 "GET /static/%7B%7B%20static('js/base.js')%20%7D%7D HTTP/1.1" 404 1885
WARNING 2021-12-20 02:59:58,986 basehttp 179 "GET /static/%7B%7B%20static('js/vue-2.5.16.js')%20%7D%7D HTTP/1.1" 404 1903
WARNING 2021-12-20 02:59:58,989 basehttp 179 "GET /static/%7B%7B%20static('images/logo.png')%20%7D%7D HTTP/1.1" 404 1900
WARNING 2021-12-20 02:59:59,001 basehttp 179 "GET /static/%7B%7B%20static('js/axios-0.18.0.min.js')%20%7D%7D HTTP/1.1" 404 1921
WARNING 2021-12-20 02:59:59,014 basehttp 179 "GET /static/%7B%7B%20static('js/jquery-1.12.4.min.js')%20%7D%7D HTTP/1.1" 404 1924
WARNING 2021-12-20 02:59:59,035 basehttp 179 "GET /static/%7B%7B%20static('images/logo.png')%20%7D%7D HTTP/1.1" 404 1900
WARNING 2021-12-20 02:59:59,036 basehttp 179 "GET /static/%7B%7B%20static('js/common.js')%20%7D%7D HTTP/1.1" 404 1891
WARNING 2021-12-20 02:59:59,075 basehttp 179 "GET /static/%7B%7B%20static('js/base.js')%20%7D%7D HTTP/1.1" 404 1885
INFO 2021-12-20 03:00:22,337 basehttp 179 "GET /static/base.html HTTP/1.1" 200 6037
WARNING 2021-12-20 03:00:22,382 basehttp 179 "GET /static/%7B%7B%20static('css/reset.css')%20%7D%7D HTTP/1.1" 404 1894
WARNING 2021-12-20 03:00:22,390 basehttp 179 "GET /static/%7B%7B%20static('css/main.css')%20%7D%7D HTTP/1.1" 404 1891
WARNING 2021-12-20 03:00:22,412 basehttp 179 "GET /static/%7B%7B%20static('js/vue-2.5.16.js')%20%7D%7D HTTP/1.1" 404 1903
WARNING 2021-12-20 03:00:22,450 basehttp 179 "GET /static/%7B%7B%20static('js/axios-0.18.0.min.js')%20%7D%7D HTTP/1.1" 404 1921
WARNING 2021-12-20 03:00:22,451 basehttp 179 "GET /static/%7B%7B%20static('js/host.js')%20%7D%7D HTTP/1.1" 404 1885
WARNING 2021-12-20 03:00:22,461 basehttp 179 "GET /static/%7B%7B%20static('js/jquery-1.12.4.min.js')%20%7D%7D HTTP/1.1" 404 1924
WARNING 2021-12-20 03:00:22,485 basehttp 179 "GET /static/%7B%7B%20static('js/base.js')%20%7D%7D HTTP/1.1" 404 1885
WARNING 2021-12-20 03:00:22,487 basehttp 179 "GET /static/%7B%7B%20static('js/vue-2.5.16.js')%20%7D%7D HTTP/1.1" 404 1903
WARNING 2021-12-20 03:00:22,493 basehttp 179 "GET /static/%7B%7B%20static('js/common.js')%20%7D%7D HTTP/1.1" 404 1891
WARNING 2021-12-20 03:00:22,493 basehttp 179 "GET /static/%7B%7B%20static('images/logo.png')%20%7D%7D HTTP/1.1" 404 1900
WARNING 2021-12-20 03:00:22,502 basehttp 179 "GET /static/%7B%7B%20static('js/axios-0.18.0.min.js')%20%7D%7D HTTP/1.1" 404 1921
WARNING 2021-12-20 03:00:22,512 basehttp 179 "GET /static/%7B%7B%20static('js/jquery-1.12.4.min.js')%20%7D%7D HTTP/1.1" 404 1924
WARNING 2021-12-20 03:00:22,529 basehttp 179 "GET /static/%7B%7B%20static('images/logo.png')%20%7D%7D HTTP/1.1" 404 1900
WARNING 2021-12-20 03:00:22,531 basehttp 179 "GET /static/%7B%7B%20static('js/common.js')%20%7D%7D HTTP/1.1" 404 1891
WARNING 2021-12-20 03:00:22,559 basehttp 179 "GET /static/%7B%7B%20static('js/base.js')%20%7D%7D HTTP/1.1" 404 1885
INFO 2021-12-20 03:04:19,424 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 03:12:08,843 autoreload 257 /home/guoliangmiao/git_workdir/miduo_mall/miduo_mall/settings.py changed, reloading.
INFO 2021-12-20 03:12:09,165 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 03:14:12,853 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 03:14:59,527 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 03:16:22,055 autoreload 257 /home/guoliangmiao/git_workdir/miduo_mall/apps/users/__init__.py changed, reloading.
INFO 2021-12-20 03:16:22,242 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 03:16:45,290 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 03:16:58,175 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 03:18:21,421 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 03:52:52,206 autoreload 257 /home/guoliangmiao/git_workdir/miduo_mall/miduo_mall/urls.py changed, reloading.
INFO 2021-12-20 03:52:52,536 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 03:54:56,511 autoreload 257 /home/guoliangmiao/git_workdir/miduo_mall/miduo_mall/urls.py changed, reloading.
INFO 2021-12-20 03:54:56,811 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 03:58:35,397 autoreload 257 /home/guoliangmiao/git_workdir/miduo_mall/miduo_mall/urls.py changed, reloading.
INFO 2021-12-20 03:58:35,680 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 04:57:54,215 autoreload 257 /home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py changed, reloading.
INFO 2021-12-20 04:57:55,144 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 04:58:21,182 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 06:29:00,991 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 08:55:20,507 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 08:55:40,193 autoreload 643 Watching for file changes with StatReloader
WARNING 2021-12-20 08:55:45,850 log 225 Not Found: /
WARNING 2021-12-20 08:55:45,851 basehttp 179 "GET / HTTP/1.1" 404 2066
WARNING 2021-12-20 08:56:12,870 basehttp 179 "GET /static/register HTTP/1.1" 404 1789
WARNING 2021-12-20 08:56:24,280 log 225 Not Found: /register
WARNING 2021-12-20 08:56:24,282 basehttp 179 "GET /register HTTP/1.1" 404 2114
INFO 2021-12-20 08:56:58,418 autoreload 257 /home/guoliangmiao/git_workdir/miduo_mall/apps/users/urls.py changed, reloading.
INFO 2021-12-20 08:56:59,027 autoreload 643 Watching for file changes with StatReloader
WARNING 2021-12-20 08:57:09,588 log 225 Not Found: /register/register
WARNING 2021-12-20 08:57:09,590 basehttp 179 "GET /register/register HTTP/1.1" 404 2223
INFO 2021-12-20 08:57:22,404 autoreload 643 Watching for file changes with StatReloader
WARNING 2021-12-20 08:57:27,685 log 225 Not Found: /register/register
WARNING 2021-12-20 08:57:27,686 basehttp 179 "GET /register/register HTTP/1.1" 404 2223
WARNING 2021-12-20 08:57:28,862 log 225 Not Found: /register/register
WARNING 2021-12-20 08:57:28,868 basehttp 179 "GET /register/register HTTP/1.1" 404 2223
WARNING 2021-12-20 08:57:29,115 log 225 Not Found: /register/register
WARNING 2021-12-20 08:57:29,116 basehttp 179 "GET /register/register HTTP/1.1" 404 2223
WARNING 2021-12-20 08:57:29,374 log 225 Not Found: /register/register
WARNING 2021-12-20 08:57:29,375 basehttp 179 "GET /register/register HTTP/1.1" 404 2223
WARNING 2021-12-20 08:57:29,650 log 225 Not Found: /register/register
WARNING 2021-12-20 08:57:29,651 basehttp 179 "GET /register/register HTTP/1.1" 404 2223
INFO 2021-12-20 08:58:11,296 autoreload 257 /home/guoliangmiao/git_workdir/miduo_mall/apps/users/urls.py changed, reloading.
INFO 2021-12-20 08:58:11,822 autoreload 643 Watching for file changes with StatReloader
WARNING 2021-12-20 08:58:27,286 log 225 Not Found: /register/
WARNING 2021-12-20 08:58:27,287 basehttp 179 "GET /register/ HTTP/1.1" 404 2190
WARNING 2021-12-20 08:58:28,955 log 225 Not Found: /register/
WARNING 2021-12-20 08:58:28,956 basehttp 179 "GET /register/ HTTP/1.1" 404 2190
WARNING 2021-12-20 08:58:29,734 log 225 Not Found: /register/
WARNING 2021-12-20 08:58:29,735 basehttp 179 "GET /register/ HTTP/1.1" 404 2190
WARNING 2021-12-20 08:58:29,944 log 225 Not Found: /register/
WARNING 2021-12-20 08:58:29,945 basehttp 179 "GET /register/ HTTP/1.1" 404 2190
WARNING 2021-12-20 08:58:30,572 log 225 Not Found: /register/
WARNING 2021-12-20 08:58:30,573 basehttp 179 "GET /register/ HTTP/1.1" 404 2190
WARNING 2021-12-20 08:58:30,696 log 225 Not Found: /register/
WARNING 2021-12-20 08:58:30,696 basehttp 179 "GET /register/ HTTP/1.1" 404 2190
WARNING 2021-12-20 08:58:30,909 log 225 Not Found: /register/
WARNING 2021-12-20 08:58:30,910 basehttp 179 "GET /register/ HTTP/1.1" 404 2190
WARNING 2021-12-20 08:58:31,541 log 225 Not Found: /register/
WARNING 2021-12-20 08:58:31,542 basehttp 179 "GET /register/ HTTP/1.1" 404 2190
INFO 2021-12-20 09:01:17,153 autoreload 257 /home/guoliangmiao/git_workdir/miduo_mall/apps/users/urls.py changed, reloading.
INFO 2021-12-20 09:01:17,697 autoreload 643 Watching for file changes with StatReloader
ERROR 2021-12-20 09:01:20,555 log 225 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: as_view() takes 1 positional argument but 2 were given
ERROR 2021-12-20 09:01:20,556 basehttp 179 "GET /register/ HTTP/1.1" 500 64929
ERROR 2021-12-20 09:01:55,170 log 225 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: as_view() takes 1 positional argument but 2 were given
ERROR 2021-12-20 09:01:55,171 basehttp 179 "GET /register/ HTTP/1.1" 500 64792
INFO 2021-12-20 09:03:11,302 autoreload 643 Watching for file changes with StatReloader
ERROR 2021-12-20 09:03:15,350 log 225 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: as_view() takes 1 positional argument but 2 were given
ERROR 2021-12-20 09:03:15,352 basehttp 179 "GET /register/ HTTP/1.1" 500 64929
INFO 2021-12-20 09:05:11,407 autoreload 643 Watching for file changes with StatReloader
WARNING 2021-12-20 09:05:16,693 log 225 Not Found: /register/
WARNING 2021-12-20 09:05:16,694 basehttp 179 "GET /register/ HTTP/1.1" 404 2190
WARNING 2021-12-20 09:05:18,250 log 225 Not Found: /register/
WARNING 2021-12-20 09:05:18,252 basehttp 179 "GET /register/ HTTP/1.1" 404 2190
INFO 2021-12-20 09:07:35,061 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 09:08:19,490 autoreload 643 Watching for file changes with StatReloader
WARNING 2021-12-20 09:09:15,552 log 225 Not Found: /register/
WARNING 2021-12-20 09:09:15,553 basehttp 179 "GET /register/ HTTP/1.1" 404 2190
INFO 2021-12-20 09:10:19,602 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 09:10:25,662 basehttp 179 "GET /register/ HTTP/1.1" 200 10697
WARNING 2021-12-20 09:10:25,707 basehttp 179 "GET /static/admin/css/fonts.css HTTP/1.1" 404 1822
INFO 2021-12-20 09:10:59,307 autoreload 257 /home/guoliangmiao/git_workdir/miduo_mall/miduo_mall/urls.py changed, reloading.
INFO 2021-12-20 09:10:59,830 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 09:12:12,530 autoreload 643 Watching for file changes with StatReloader
WARNING 2021-12-20 09:12:19,953 log 225 Not Found: /register/
WARNING 2021-12-20 09:12:19,953 basehttp 179 "GET /register/ HTTP/1.1" 404 2190
WARNING 2021-12-20 09:12:21,067 log 225 Not Found: /register/
WARNING 2021-12-20 09:12:21,067 basehttp 179 "GET /register/ HTTP/1.1" 404 2190
INFO 2021-12-20 09:13:03,307 autoreload 257 /home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py changed, reloading.
INFO 2021-12-20 09:13:03,764 autoreload 643 Watching for file changes with StatReloader
WARNING 2021-12-20 09:13:08,295 log 225 Not Found: /register/
WARNING 2021-12-20 09:13:08,297 basehttp 179 "GET /register/ HTTP/1.1" 404 2190
INFO 2021-12-20 09:16:46,912 autoreload 643 Watching for file changes with StatReloader
WARNING 2021-12-20 09:16:50,983 log 225 Not Found: /register/
WARNING 2021-12-20 09:16:50,984 basehttp 179 "GET /register/ HTTP/1.1" 404 2190
WARNING 2021-12-20 09:16:52,088 log 225 Not Found: /register/
WARNING 2021-12-20 09:16:52,089 basehttp 179 "GET /register/ HTTP/1.1" 404 2190
WARNING 2021-12-20 09:16:52,283 log 225 Not Found: /register/
WARNING 2021-12-20 09:16:52,284 basehttp 179 "GET /register/ HTTP/1.1" 404 2190
WARNING 2021-12-20 09:16:52,473 log 225 Not Found: /register/
WARNING 2021-12-20 09:16:52,474 basehttp 179 "GET /register/ HTTP/1.1" 404 2190
INFO 2021-12-20 09:18:01,782 autoreload 643 Watching for file changes with StatReloader
WARNING 2021-12-20 09:18:05,910 log 225 Not Found: /register/
WARNING 2021-12-20 09:18:05,911 basehttp 179 "GET /register/ HTTP/1.1" 404 2189
WARNING 2021-12-20 09:18:11,199 log 225 Not Found: /register/
WARNING 2021-12-20 09:18:11,201 basehttp 179 "GET /register/ HTTP/1.1" 404 2189
INFO 2021-12-20 09:18:25,328 autoreload 257 /home/guoliangmiao/git_workdir/miduo_mall/apps/users/urls.py changed, reloading.
INFO 2021-12-20 09:18:25,842 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 09:22:09,343 autoreload 257 /home/guoliangmiao/git_workdir/miduo_mall/miduo_mall/urls.py changed, reloading.
INFO 2021-12-20 09:22:09,952 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 09:23:07,552 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 09:26:27,572 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 09:31:35,975 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 09:32:51,850 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 09:33:08,086 autoreload 643 Watching for file changes with StatReloader
WARNING 2021-12-20 09:34:08,780 log 225 Not Found: /register
WARNING 2021-12-20 09:34:08,781 basehttp 179 "GET /register HTTP/1.1" 404 2114
WARNING 2021-12-20 09:34:13,054 log 225 Not Found: /register/
WARNING 2021-12-20 09:34:13,059 basehttp 179 "GET /register/ HTTP/1.1" 404 2190
INFO 2021-12-20 09:35:42,255 basehttp 179 "GET /register/register HTTP/1.1" 301 0
ERROR 2021-12-20 09:35:42,313 log 225 Internal Server Error: /register/register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: as_view() takes 1 positional argument but 2 were given
ERROR 2021-12-20 09:35:42,315 basehttp 179 "GET /register/register/ HTTP/1.1" 500 64873
INFO 2021-12-20 09:36:44,165 autoreload 643 Watching for file changes with StatReloader
ERROR 2021-12-20 09:36:47,561 log 225 Internal Server Error: /register/register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py", line 8, in get
    return render(request, "register.html")
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/backends/jinja2.py", line 74, in render
    return self.template.render(context)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/guoliangmiao/git_workdir/miduo_mall/templates/register.html", line 23, in top-level template code
    <a href="{{ url('users:login') }}">登录</a>
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2021-12-20 09:36:47,565 basehttp 179 "GET /register/register/ HTTP/1.1" 500 121563
INFO 2021-12-20 09:37:39,089 autoreload 643 Watching for file changes with StatReloader
WARNING 2021-12-20 09:37:43,380 log 225 Not Found: /register/register/
WARNING 2021-12-20 09:37:43,382 basehttp 179 "GET /register/register/ HTTP/1.1" 404 2208
ERROR 2021-12-20 09:37:50,389 log 225 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py", line 8, in get
    return render(request, "register.html")
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/backends/jinja2.py", line 74, in render
    return self.template.render(context)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/guoliangmiao/git_workdir/miduo_mall/templates/register.html", line 23, in top-level template code
    <a href="{{ url('users:login') }}">登录</a>
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2021-12-20 09:37:50,392 basehttp 179 "GET /register/ HTTP/1.1" 500 121765
INFO 2021-12-20 09:42:06,393 autoreload 643 Watching for file changes with StatReloader
ERROR 2021-12-20 09:42:09,444 log 225 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py", line 8, in get
    return render(request, "register.html")
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/backends/jinja2.py", line 74, in render
    return self.template.render(context)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/guoliangmiao/git_workdir/miduo_mall/templates/register.html", line 23, in top-level template code
    <a href="{{ url('users:login') }}">登录</a>
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2021-12-20 09:42:09,447 basehttp 179 "GET /register/ HTTP/1.1" 500 121902
ERROR 2021-12-20 09:42:10,520 log 225 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py", line 8, in get
    return render(request, "register.html")
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/backends/jinja2.py", line 74, in render
    return self.template.render(context)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/guoliangmiao/git_workdir/miduo_mall/templates/register.html", line 23, in top-level template code
    <a href="{{ url('users:login') }}">登录</a>
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2021-12-20 09:42:10,523 basehttp 179 "GET /register/ HTTP/1.1" 500 121902
ERROR 2021-12-20 09:42:10,858 log 225 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py", line 8, in get
    return render(request, "register.html")
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/backends/jinja2.py", line 74, in render
    return self.template.render(context)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/guoliangmiao/git_workdir/miduo_mall/templates/register.html", line 23, in top-level template code
    <a href="{{ url('users:login') }}">登录</a>
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2021-12-20 09:42:10,859 basehttp 179 "GET /register/ HTTP/1.1" 500 121902
INFO 2021-12-20 15:35:49,345 autoreload 643 Watching for file changes with StatReloader
WARNING 2021-12-20 15:35:57,007 log 225 Not Found: /
WARNING 2021-12-20 15:35:57,008 basehttp 179 "GET / HTTP/1.1" 404 2066
INFO 2021-12-20 15:36:12,854 basehttp 179 "GET /register HTTP/1.1" 301 0
ERROR 2021-12-20 15:36:12,970 log 225 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py", line 8, in get
    return render(request, "register.html")
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/backends/jinja2.py", line 74, in render
    return self.template.render(context)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/guoliangmiao/git_workdir/miduo_mall/templates/register.html", line 23, in top-level template code
    <a href="{{ url('users:login') }}">登录</a>
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2021-12-20 15:36:12,974 basehttp 179 "GET /register/ HTTP/1.1" 500 122285
INFO 2021-12-20 15:38:01,392 autoreload 257 /home/guoliangmiao/git_workdir/miduo_mall/apps/users/urls.py changed, reloading.
INFO 2021-12-20 15:38:01,880 autoreload 643 Watching for file changes with StatReloader
WARNING 2021-12-20 15:38:20,560 log 225 Not Found: /register
WARNING 2021-12-20 15:38:20,575 log 225 Not Found: /register/
WARNING 2021-12-20 15:38:20,576 basehttp 179 "GET /register/ HTTP/1.1" 404 2176
WARNING 2021-12-20 15:38:20,747 log 225 Not Found: /favicon.ico
WARNING 2021-12-20 15:38:24,135 log 225 Not Found: /register/
WARNING 2021-12-20 15:38:24,136 basehttp 179 "GET /register/ HTTP/1.1" 404 2176
WARNING 2021-12-20 15:41:13,609 log 225 Not Found: /register/
WARNING 2021-12-20 15:41:13,610 basehttp 179 "GET /register/ HTTP/1.1" 404 2182
WARNING 2021-12-20 15:41:13,738 log 225 Not Found: /favicon.ico
INFO 2021-12-20 15:41:43,763 autoreload 643 Watching for file changes with StatReloader
ERROR 2021-12-20 15:42:02,835 log 225 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py", line 8, in get
    return render(request, "register.html")
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/backends/jinja2.py", line 74, in render
    return self.template.render(context)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/guoliangmiao/git_workdir/miduo_mall/templates/register.html", line 23, in top-level template code
    <a href="{{ url('users:login') }}">登录</a>
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2021-12-20 15:42:02,838 basehttp 179 "GET /register/ HTTP/1.1" 500 121902
INFO 2021-12-20 15:51:17,791 autoreload 257 /home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py changed, reloading.
INFO 2021-12-20 15:51:18,882 autoreload 643 Watching for file changes with StatReloader
INFO 2021-12-20 15:55:29,629 autoreload 643 Watching for file changes with StatReloader
ERROR 2021-12-20 15:55:38,302 log 225 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py", line 8, in get
    render(request, 'register.html')
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/backends/jinja2.py", line 74, in render
    return self.template.render(context)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/guoliangmiao/git_workdir/miduo_mall/templates/register.html", line 23, in top-level template code
    <a href="{{ url('users:login') }}">登录</a>
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2021-12-20 15:55:38,307 basehttp 179 "GET /register/ HTTP/1.1" 500 121880
ERROR 2021-12-20 15:55:39,284 log 225 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py", line 8, in get
    render(request, 'register.html')
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/backends/jinja2.py", line 74, in render
    return self.template.render(context)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/guoliangmiao/git_workdir/miduo_mall/templates/register.html", line 23, in top-level template code
    <a href="{{ url('users:login') }}">登录</a>
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2021-12-20 15:55:39,286 basehttp 179 "GET /register/ HTTP/1.1" 500 121880
ERROR 2021-12-20 15:55:40,168 log 225 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py", line 8, in get
    render(request, 'register.html')
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/backends/jinja2.py", line 74, in render
    return self.template.render(context)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/guoliangmiao/git_workdir/miduo_mall/templates/register.html", line 23, in top-level template code
    <a href="{{ url('users:login') }}">登录</a>
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2021-12-20 15:55:40,170 basehttp 179 "GET /register/ HTTP/1.1" 500 121880
ERROR 2021-12-20 15:55:40,588 log 225 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py", line 8, in get
    render(request, 'register.html')
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/backends/jinja2.py", line 74, in render
    return self.template.render(context)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/guoliangmiao/git_workdir/miduo_mall/templates/register.html", line 23, in top-level template code
    <a href="{{ url('users:login') }}">登录</a>
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2021-12-20 15:55:40,590 basehttp 179 "GET /register/ HTTP/1.1" 500 121880
ERROR 2021-12-20 15:55:57,199 log 225 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py", line 8, in get
    render(request, 'register.html')
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/backends/jinja2.py", line 74, in render
    return self.template.render(context)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/guoliangmiao/git_workdir/miduo_mall/templates/register.html", line 23, in top-level template code
    <a href="{{ url('users:login') }}">登录</a>
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2021-12-20 15:55:57,202 basehttp 179 "GET /register/ HTTP/1.1" 500 121743
WARNING 2021-12-20 15:55:57,265 log 225 Not Found: /favicon.ico
WARNING 2021-12-20 15:55:57,266 basehttp 179 "GET /favicon.ico HTTP/1.1" 404 2123
INFO 2021-12-20 15:57:55,604 autoreload 643 Watching for file changes with StatReloader
ERROR 2021-12-20 15:58:00,129 log 225 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py", line 8, in get
    return render(request, 'register.html')
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/backends/jinja2.py", line 74, in render
    return self.template.render(context)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/guoliangmiao/git_workdir/miduo_mall/templates/register.html", line 23, in top-level template code
    <a href="{{ url('users:login') }}">登录</a>
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2021-12-20 15:58:00,131 basehttp 179 "GET /register/ HTTP/1.1" 500 121894
ERROR 2021-12-20 15:58:01,143 log 225 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py", line 8, in get
    return render(request, 'register.html')
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/backends/jinja2.py", line 74, in render
    return self.template.render(context)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/guoliangmiao/git_workdir/miduo_mall/templates/register.html", line 23, in top-level template code
    <a href="{{ url('users:login') }}">登录</a>
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2021-12-20 15:58:01,145 basehttp 179 "GET /register/ HTTP/1.1" 500 121894
ERROR 2021-12-20 15:58:01,481 log 225 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py", line 8, in get
    return render(request, 'register.html')
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/backends/jinja2.py", line 74, in render
    return self.template.render(context)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/guoliangmiao/git_workdir/miduo_mall/templates/register.html", line 23, in top-level template code
    <a href="{{ url('users:login') }}">登录</a>
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2021-12-20 15:58:01,483 basehttp 179 "GET /register/ HTTP/1.1" 500 121894
ERROR 2021-12-20 15:58:01,712 log 225 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py", line 8, in get
    return render(request, 'register.html')
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/backends/jinja2.py", line 74, in render
    return self.template.render(context)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/guoliangmiao/git_workdir/miduo_mall/templates/register.html", line 23, in top-level template code
    <a href="{{ url('users:login') }}">登录</a>
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2021-12-20 15:58:01,714 basehttp 179 "GET /register/ HTTP/1.1" 500 121894
ERROR 2021-12-20 15:58:01,954 log 225 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py", line 8, in get
    return render(request, 'register.html')
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/backends/jinja2.py", line 74, in render
    return self.template.render(context)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/guoliangmiao/git_workdir/miduo_mall/templates/register.html", line 23, in top-level template code
    <a href="{{ url('users:login') }}">登录</a>
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2021-12-20 15:58:01,955 basehttp 179 "GET /register/ HTTP/1.1" 500 121894
ERROR 2021-12-20 15:58:03,149 log 225 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py", line 8, in get
    return render(request, 'register.html')
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/backends/jinja2.py", line 74, in render
    return self.template.render(context)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/guoliangmiao/git_workdir/miduo_mall/templates/register.html", line 23, in top-level template code
    <a href="{{ url('users:login') }}">登录</a>
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2021-12-20 15:58:03,150 basehttp 179 "GET /register/ HTTP/1.1" 500 121894
ERROR 2021-12-20 15:58:04,189 log 225 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py", line 8, in get
    return render(request, 'register.html')
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/backends/jinja2.py", line 74, in render
    return self.template.render(context)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/guoliangmiao/git_workdir/miduo_mall/templates/register.html", line 23, in top-level template code
    <a href="{{ url('users:login') }}">登录</a>
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2021-12-20 15:58:04,191 basehttp 179 "GET /register/ HTTP/1.1" 500 121894
INFO 2021-12-20 16:00:44,821 autoreload 643 Watching for file changes with StatReloader
ERROR 2021-12-20 16:00:50,701 log 225 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py", line 8, in get
    return render(request, 'register.html')
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/backends/jinja2.py", line 74, in render
    return self.template.render(context)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/guoliangmiao/git_workdir/miduo_mall/templates/register.html", line 23, in top-level template code
    <a href="{{ url('users:login') }}">登录</a>
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2021-12-20 16:00:50,708 basehttp 179 "GET /register/ HTTP/1.1" 500 121894
ERROR 2021-12-20 16:00:51,825 log 225 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py", line 8, in get
    return render(request, 'register.html')
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/backends/jinja2.py", line 74, in render
    return self.template.render(context)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/guoliangmiao/git_workdir/miduo_mall/templates/register.html", line 23, in top-level template code
    <a href="{{ url('users:login') }}">登录</a>
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2021-12-20 16:00:51,825 basehttp 179 "GET /register/ HTTP/1.1" 500 121894
ERROR 2021-12-20 16:00:52,058 log 225 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py", line 8, in get
    return render(request, 'register.html')
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/backends/jinja2.py", line 74, in render
    return self.template.render(context)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/guoliangmiao/git_workdir/miduo_mall/templates/register.html", line 23, in top-level template code
    <a href="{{ url('users:login') }}">登录</a>
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2021-12-20 16:00:52,060 basehttp 179 "GET /register/ HTTP/1.1" 500 121894
ERROR 2021-12-20 16:00:52,317 log 225 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/guoliangmiao/git_workdir/miduo_mall/apps/users/views.py", line 8, in get
    return render(request, 'register.html')
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/template/backends/jinja2.py", line 74, in render
    return self.template.render(context)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/guoliangmiao/git_workdir/miduo_mall/templates/register.html", line 23, in top-level template code
    <a href="{{ url('users:login') }}">登录</a>
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/guoliangmiao/.virtualenvs/miduo_mall/lib/python3.8/site-packages/django/urls/resolvers.py", line 729, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2021-12-20 16:00:52,319 basehttp 179 "GET /register/ HTTP/1.1" 500 121894
INFO 2021-12-20 16:06:09,103 basehttp 179 "GET /register/ HTTP/1.1" 200 3282
INFO 2021-12-20 16:06:09,193 basehttp 179 "GET /static/css/reset.css HTTP/1.1" 200 638
INFO 2021-12-20 16:06:09,193 basehttp 179 "GET /static/js/common.js HTTP/1.1" 200 891
INFO 2021-12-20 16:06:09,196 basehttp 179 "GET /static/js/host.js HTTP/1.1" 200 80
INFO 2021-12-20 16:06:09,198 basehttp 179 "GET /static/js/register.js HTTP/1.1" 200 8920
INFO 2021-12-20 16:06:09,199 basehttp 179 "GET /static/css/main.css HTTP/1.1" 200 39722
INFO 2021-12-20 16:06:09,204 basehttp 179 "GET /static/images/pic_code.jpg HTTP/1.1" 200 4507
INFO 2021-12-20 16:06:09,205 basehttp 179 "GET /static/images/logo.png HTTP/1.1" 200 7450
INFO 2021-12-20 16:06:09,215 basehttp 179 "GET /static/images/interval_line.png HTTP/1.1" 200 1123
INFO 2021-12-20 16:06:09,219 basehttp 179 "GET /static/images/register_banner.png HTTP/1.1" 200 54894
INFO 2021-12-20 16:06:09,221 basehttp 179 "GET /static/images/icons02.png HTTP/1.1" 200 3935
